### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by slim1592** [henrymaas/AudioSlicer#9]
Splitting C:\Users\Slim\Desktop\vocals\blabla.wav where energy is below 0.01% for longer than 0.6s.
Traceback (most recent call last):
  File "C:\Users\Slim\AudioSlicer\AudioSeg.py", line 93, in <module>
    max_amplitude = np.iinfo(samples.dtype).max
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Slim\anaconda3\envs\audioslicer\Lib\site-packages\numpy\core\getlimits.py", line 677, in __init__
    raise ValueError("Invalid integer data type %r." % (self.kind,))
ValueError: Invalid integer data type 'f'.

**Comment by henrymaas** [comment]
It seems that the algorithm is unable to process the file correctly. 
Was this audio file previously converted? The variety of issues that might occur can depend on the specific piece of audio provided. Therefore, I can only provide you with assistance if I have the file at hand. I would suggest trying another audio file to see if this problem occurs frequently.

Please let me know if there is anything else I can do to assist you.

**Comment by arunk140** [comment]
samples.dtype is probably a Float. and np.iinfo expects dtype to be ints

**Comment by rajatdb** [comment]
replace np.iinfo(samples.dtype).max to np.finfo(samples.dtype).max

**Comment by henrymaas** [comment]
Try to export your Wav file in int16 format
